# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:

jobs:
  build:
    strategy: 
      matrix:
        # buildroot uses 1.19, so we want to sanity check that too
        version: ['1.19', '1.20']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Install Protoc-Gen-Go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Build
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        protoc --go_out=./proto-out --go-grpc_out=require_unimplemented_servers=false:./proto-out --proto_path=./proto/hm -I=./proto/hm ./proto/hm/sensordata.proto
        GOOS=linux GOARCH=arm64 go build ./cmd/datalogger

    # TODO: add tests?
